FRANKFURT
----------

SELECT COUNT(*) FROM CUSTOMERS;

SELECT * FROM CUSTOMERS WHERE CUSTOMER_ID=4000;
SELECT * FROM CUSTOMERS WHERE CUSTOMER_ID=5000;
SELECT * FROM CUSTOMERS WHERE CUSTOMER_ID=6000;


insert into customers (CUSTOMER_ID,EMAIL_ADDRESS,FULL_NAME) values (4000,'NEO@internalmail','NEO MATRIX');
COMMIT;

SINGAPORE
----------

SELECT COUNT(*) FROM CUSTOMERS;

SELECT * FROM CUSTOMERS WHERE CUSTOMER_ID=4000;
SELECT * FROM CUSTOMERS WHERE CUSTOMER_ID=5000;
SELECT * FROM CUSTOMERS WHERE CUSTOMER_ID=6000;


insert into customers (CUSTOMER_ID,EMAIL_ADDRESS,FULL_NAME) values (5000,'AGENT.SMITH@internalmail','AGENT SMITH');
COMMIT;

SYDNEY
----------

SELECT COUNT(*) FROM CUSTOMERS;

SELECT * FROM CUSTOMERS WHERE CUSTOMER_ID=4000;
SELECT * FROM CUSTOMERS WHERE CUSTOMER_ID=5000;
SELECT * FROM CUSTOMERS WHERE CUSTOMER_ID=6000;


insert into customers (CUSTOMER_ID,EMAIL_ADDRESS,FULL_NAME) values (6000,'ORACLE@internalmail','ORACLE');
COMMIT;
